vim.g.mapleader = " "

vim.keymap.set("n", "<Space>", "<Nop>", { silent = true, remap = false })

require("bsteffaniak/savesession")

vim.keymap.set({"n", "v"}, "m", "n")
vim.keymap.set({"n", "v"}, "M", "N")
vim.keymap.set({"n", "v"}, "h", "<left>", {noremap = true})
vim.keymap.set({"n", "v"}, "t", "<down>", {noremap = true})
vim.keymap.set({"n", "v"}, "n", "<up>", {noremap = true})
vim.keymap.set({"n", "v"}, "s", "<right>", {noremap = true})
vim.keymap.set("n", "<Leader>o", "o<Esc>", {noremap = true})
vim.keymap.set("n", "<Leader>O", "O<Esc>", {noremap = true})
vim.keymap.set("n", "<Leader>e", ":GFiles<Enter>", {noremap = true})
vim.keymap.set("n", "<Leader><Leader>", ":Files<Enter>", {noremap = true})
vim.keymap.set("n", "<Leader>t", ":NvimTreeToggle<Enter>", {noremap = true})
vim.keymap.set("n", "<Leader>g", ":NvimTreeFindFile<Enter>", {noremap = true})
vim.keymap.set("n", "<Leader>c", ":NvimTreeCollapse<Enter>", {noremap = true})
vim.keymap.set("n", "<Leader>f", ":Rg<Enter>", {noremap = true})
vim.keymap.set("n", "<Leader>b", ":Telescope buffers<Enter>", {noremap = true})
vim.keymap.set("n", "<Leader>s", Handle_save_session, {noremap = true})
vim.keymap.set("n", "<Leader>S", ":mksession! ~/", {noremap = true})
vim.keymap.set("n", "<Leader>q", Handle_save_and_quit, {noremap = true})
vim.keymap.set("n", "<Leader>Q", Handle_force_save_and_quit, {noremap = true})
vim.keymap.set("n", "<Leader>l", Handle_load_session, {noremap = true})
vim.keymap.set("n", "<Leader>L", ":source ~/", {noremap = true})
vim.keymap.set("n", "<Leader>;", "@:", {noremap = true})
vim.keymap.set({"n", "v", "i"}, "<M-ScrollWheelUp>", "<ScrollWheelLeft>", {noremap = true})
vim.keymap.set({"n", "v", "i"}, "<M-ScrollWheelDown>", "<ScrollWheelRight>", {noremap = true})
vim.keymap.set({"n", "v"}, ";", "l", {noremap = true})
vim.keymap.set({"n", "v"}, "l", "k", {noremap = true})
vim.keymap.set({"n", "v"}, "k", "j", {noremap = true})
vim.keymap.set({"n", "v"}, "j", "h", {noremap = true})
vim.keymap.set({"n", "v", "i"}, "<c-w>;", "<c-w><right>", {noremap = true})
vim.keymap.set({"n", "v", "i"}, "<c-w>l", "<c-w><up>", {noremap = true})
vim.keymap.set({"n", "v", "i"}, "<c-w>k", "<c-w><down>", {noremap = true})
vim.keymap.set({"n", "v", "i"}, "<c-w>j", "<c-w><left>", {noremap = true})
vim.keymap.set({"n", "v"}, "<Leader>.u", ":GitGutterUndoHunk<Enter>", {noremap = true})
vim.keymap.set({"n", "v"}, "<Leader>.]", ":GitGutterNextHunk<Enter>", {noremap = true})
vim.keymap.set({"n", "v"}, "<Leader>.[", ":GitGutterPrevHunk<Enter>", {noremap = true})

local maximize = require('maximize')

vim.keymap.set({"n", "v"}, "<Leader><Tab>", function()
  maximize.restore()
  vim.cmd(vim.api.nvim_replace_termcodes("normal <c-w>w", true, true, true))
  maximize.maximize()
end, {noremap = true})

